version: '3.8'
services:
  back_ecommerce_dcompose:
    build: ./ 
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - postgres_ecommerce_dcompose

  postgres_ecommerce_dcompose:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata: